# Generated by Django 4.2.1 on 2023-06-07 23:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('new_ride', '0004_alter_new_ride_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_ride',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
